[phases.setup]
nixPkgs = { python = "3.11" }

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --no-input"
]

[start]
cmd = "python -m gunicorn master.wsgi:application --bind 0.0.0.0:$PORT"

